### ISSUE TITLE
Create a Hindi translation of the open terminal guide

### ISSUE THREAD

**Issue by devadvance** [devadvance/terminalcheatsheet#68]
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/open-terminal-macos.md), create a Hindi translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/hi/guides/open-terminal-macos.md.

It is OK to use the English images/GIFs.

**Comment by navya252001** [comment]
Sir please help me in HACKTOBER FEST 2020
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
Latest guidelines issued by the organizers
I sincerely hope you will help me
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convenience

**Comment by navya252001** [comment]
Please assign it to me
Also you want it all in हिंदी के शब्द?

**Comment by devadvance** [comment]
Assigned!

**Comment by navya252001** [comment]
I have submitted the PR pls review

**Comment by navya252001** [comment]
I just need this one PR merge to complete my 4 PR rqsts for Hacktober...

**Comment by devadvance** [comment]
Left some comments on the PR for your review.

**Comment by devadvance** [comment]
@navya252001 Merge your PR (#77). Thanks!

**Comment by navya252001** [comment]
Thankyou
